<?xml version="1.0" encoding="UTF-8"?>
<testsuites>
  <testsuite name="/home/pouria/Desktop/Connect/phpunit.xml" tests="9" assertions="35" errors="0" failures="1" skipped="0" time="1.389172">
    <testsuite name="Feature" tests="9" assertions="35" errors="0" failures="1" skipped="0" time="1.389172">
      <testsuite name="Tests\Feature\AuthControllerTest" file="/home/pouria/Desktop/Connect/tests/Feature/AuthControllerTest.php" tests="9" assertions="35" errors="0" failures="1" skipped="0" time="1.389172">
        <testcase name="test_user_can_request_otp" file="/home/pouria/Desktop/Connect/tests/Feature/AuthControllerTest.php" line="14" class="Tests\Feature\AuthControllerTest" classname="Tests.Feature.AuthControllerTest" assertions="4" time="0.812062">
          <system-out> </system-out>
        </testcase>
        <testcase name="test_user_can_verify_otp" file="/home/pouria/Desktop/Connect/tests/Feature/AuthControllerTest.php" line="31" class="Tests\Feature\AuthControllerTest" classname="Tests.Feature.AuthControllerTest" assertions="4" time="0.059684">
          <system-out> </system-out>
        </testcase>
        <testcase name="test_user_cannot_verify_expired_otp" file="/home/pouria/Desktop/Connect/tests/Feature/AuthControllerTest.php" line="57" class="Tests\Feature\AuthControllerTest" classname="Tests.Feature.AuthControllerTest" assertions="2" time="0.073338">
          <system-out> </system-out>
        </testcase>
        <testcase name="test_user_cannot_verify_used_otp" file="/home/pouria/Desktop/Connect/tests/Feature/AuthControllerTest.php" line="77" class="Tests\Feature\AuthControllerTest" classname="Tests.Feature.AuthControllerTest" assertions="2" time="0.052116">
          <system-out> </system-out>
        </testcase>
        <testcase name="test_existing_user_can_login_with_valid_otp" file="/home/pouria/Desktop/Connect/tests/Feature/AuthControllerTest.php" line="97" class="Tests\Feature\AuthControllerTest" classname="Tests.Feature.AuthControllerTest" assertions="4" time="0.053536">
          <system-out> </system-out>
        </testcase>
        <testcase name="test_user_can_register_with_valid_otp" file="/home/pouria/Desktop/Connect/tests/Feature/AuthControllerTest.php" line="123" class="Tests\Feature\AuthControllerTest" classname="Tests.Feature.AuthControllerTest" assertions="9" time="0.069511">
          <system-out> </system-out>
        </testcase>
        <testcase name="test_user_cannot_register_without_verifying_otp" file="/home/pouria/Desktop/Connect/tests/Feature/AuthControllerTest.php" line="166" class="Tests\Feature\AuthControllerTest" classname="Tests.Feature.AuthControllerTest" assertions="2" time="0.051225">
          <system-out> </system-out>
        </testcase>
        <testcase name="test_user_can_register_with_referral_code" file="/home/pouria/Desktop/Connect/tests/Feature/AuthControllerTest.php" line="183" class="Tests\Feature\AuthControllerTest" classname="Tests.Feature.AuthControllerTest" assertions="7" time="0.105182">
          <system-out> </system-out>
        </testcase>
        <testcase name="test_provider_can_register_with_valid_otp" file="/home/pouria/Desktop/Connect/tests/Feature/AuthControllerTest.php" line="233" class="Tests\Feature\AuthControllerTest" classname="Tests.Feature.AuthControllerTest" assertions="1" time="0.112518">
          <failure type="PHPUnit\Framework\ExpectationFailedException">Tests\Feature\AuthControllerTest::test_provider_can_register_with_valid_otp
Expected response status code [200] but received 500.
Failed asserting that 500 is identical to 200.

/home/pouria/Desktop/Connect/vendor/laravel/framework/src/Illuminate/Testing/TestResponseAssert.php:45
/home/pouria/Desktop/Connect/vendor/laravel/framework/src/Illuminate/Testing/TestResponse.php:159
/home/pouria/Desktop/Connect/tests/Feature/AuthControllerTest.php:268</failure>
          <system-out> </system-out>
        </testcase>
      </testsuite>
    </testsuite>
  </testsuite>
</testsuites>
